### ISSUE TITLE
Failing on assert

### ISSUE THREAD

**Issue by exander77** [ondt/dpp-cli#1]
Hi, it fails for me with this error:

```
Traceback (most recent call last):
  File "./dpp.py", line 31, in <module>
    title, connections = dpp.query_connection(src=args.start, dst=args.end, via=args.via, num=args.n)
  File "/home/polach/repos/dpp-cli/core/web.py", line 100, in query_connection
    assert "frmResult" in res.text, "unknown response received"
AssertionError: unknown response received
```

**Comment by ondt** [comment]
Hi, it looks like they have completely changed the design (and structure) of the website. I'll look into it ASAP.

**Comment by exander77** [comment]
@ondt  Thank you for the prompt response. I would like to integrate this into my home automation to get connections, so if this works, I will be making pull request soon with JSON output.

**Comment by ondt** [comment]
Hello, it works now. The JSON and PDF output works as well.
